name: Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

#### Test and scan code ####
  test_and_scan_code:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt
        pip install bandit

    - name: Run unit tests
      run: |
        cd app
        pytest

    - name: Run Bandit (code scan)
      run: |
        bandit -r app -ll

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

##### TF Deploy to GCP #####
  terraform_deploy_gcp:

    runs-on: ubuntu-latest
    needs: test_and_scan_code

    steps:
    - uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform fmt
      working-directory: iac
      run: |
        terraform fmt 

    - name: Terraform init
      working-directory: iac
      run: |
        terraform init

    - name: Terraform validate
      working-directory: iac
      run: |
        terraform validate


    - name: Terraform plan
      working-directory: iac
      run: |
        terraform plan -out="plan.tfplan" -lock=false

    - name: Terraform apply
      working-directory: iac
      run: |
        terraform apply -auto-approve plan.tfplan