name: Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:


##### TF Deploy to GCP #####
  terraform_deploy_gcp:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform fmt
      working-directory: iac
      run: |
        terraform fmt 

    - name: Terraform init
      working-directory: iac
      run: |
        terraform init

    - name: Terraform validate
      working-directory: iac
      run: |
        terraform validate


    - name: Terraform plan
      working-directory: iac
      run: |
        terraform plan -out="plan.tfplan" -lock=false

